flowchart
    start((start)) -->
    clearTerminal(clear the terminal) -->
    consoleObject(create new console object) -->
    restaurantFiles(store all filenames of the menus in a tuple called restaurant_files) -->
    locations(store all the locations of the restaurants in a tuple called locations) -->
    emptyRestaurant(store empty dictionary to restaurant) -->
    lastItemInRestaurantFiles{Is this the last item in restaurant files?} --> |Yes| lastItemInRestaurantKeys{Is this last item in restaurant keys?}
    lastItemInRestaurantKeys --> |No| printIndexRestaurant
    lastItemInRestaurantFiles --> |No| createRestaurantItem(create new restaurant object at index restaurant name) --> lastItemInRestaurantFiles    