flowchart
    start((start)) -->
    clearTerminal(clear the terminal) -->
    consoleObject(create new console object) -->
    restaurantFiles(store all filenames of the menus in a list called restaurant_files) -->
    